name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [node, python]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      if: matrix.language == 'node'
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js dependencies
      if: matrix.language == 'node'
      run: npm install

    - name: Build React project
      if: matrix.language == 'node'
      run: npm run build

    - name: Run React tests
      if: matrix.language == 'node'
      run: npm test

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      if: matrix.language == 'python'
      run: python manage.py test

